### ISSUE TITLE
[ENHANCEMENT]: 

### ISSUE THREAD

**Issue by 23tom2323** [hashtopolis/server#1037]
### Description

I have several computers that are on anyway, unfortunately most only support OpenCL 1.2 (AMD Radeon HD 6550D, Intel(R) HD Graphics 4600,...)

Is there a way to use the CPU (Intel Core i5-4590, AMD A8-3870,...) for the hash (WPA-PBKDF2-PMKID+EAPOL) or perhaps a possibility with openCL 1.2 to work?

**Comment by s3inlc** [comment]
This is not really a hashtopolis question. As long as hashcat is able to work with the said CPUs (most likely it will work with the Intel OpenCL installed) and GPUs (not sure if these are too old or not supported due to being on-board GPUs).
If you are unsure how to get hashcat working with this hardware, I recommend asking in their discord channel.
